version: '3.8'

services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./backend/music.db:/app/music.db
      - ./static:/app/static
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: always